'''
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
'''
from itertools import count

tri = (x / 2 * (x + 1) for x in count(1, 1))
penta = (x / 2 * (3 * x - 1) for x in count(1, 1))
hex = (x * (2 * x - 1) for x in count(1, 1))

curr_tri = next(tri)
curr_penta = next(penta)
curr_hex = next(hex)
while True:
    while curr_penta < curr_tri:
        curr_penta = next(penta)
    while curr_hex < curr_tri:
        curr_hex = next(hex)
    if curr_tri == curr_hex == curr_penta:
        print(curr_tri)
        if curr_tri > 40755:
            break
    curr_tri = next(tri)